version: '3.4'

services:
  profilewebsite:
    image: profilewebsite
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
      - ./.git:/usr/src/app/.git


